### ISSUE TITLE
Service Addition/Edit Request: TaBS

### ISSUE THREAD

**Issue by ghost** [MystPi/scratch-explorer#2]
**Name:** &lt;TaBS&gt;

**For:** &lt;community&gt;

**Theme color:** &lt;cyan&gt;

**Description:** &lt;description (*Text Based Scratch. In active development.*&gt;

**Icon:** &lt;"code"&gt;

**Forum topic (optional):** &lt;&gt;

**Username:** &lt;ToastersUnited&gt;

**Link:** &lt;https://nill2021.github.io/TaBS/&gt;

**Comment by MystPi** [comment]
Is this ready to be put on the site? It looks a bit unfinished.

**Comment by ghost** [comment]
> Is this ready to be put on the site? It looks a bit unfinished.

i don't really know. Add it when you feel it's ready.
Also forum topic now because i wanted a logo or banner to look cool https://scratch.mit.edu/discuss/topic/596216/?page=1#post-6207532

**Comment by MystPi** [comment]
Okay, I'll close this now and add it when it's ready. :)
