### ISSUE TITLE
Suggestion: Add a dark theme

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [MystPi/scratch-explorer#3]
You don't have to, just a suggestion.

**Comment by MystPi** [comment]
That would be cool, I'm just bad at designing dark mode 🤣.

**Comment by ILOVETOMAKESTUFF** [comment]
Do you mean that you don't know which shades of grey you should pick?

**Comment by ILOVETOMAKESTUFF** [comment]
I tried forking to test what grey looks good, but then I found out you used tailwind...

**Comment by MystPi** [comment]
> Do you mean that you don't know which shades of grey you should pick?

Not exactly... I'm just better at designing light-mode things.

**Comment by ILOVETOMAKESTUFF** [comment]
Okay

**Comment by ILOVETOMAKESTUFF** [comment]
All you have to do is switch the background color and font color.

**Comment by MystPi** [comment]
Well, not exactly. You would also have to change the color of the buttons, and not all of the text is the same color. It would look like this if you did that:
![image](https://user-images.githubusercontent.com/86574651/169525333-8c7b7044-2664-49ea-9d59-808a2d1dbfa4.png)

**Comment by ILOVETOMAKESTUFF** [comment]
What happened to the card at the bottom?

**Comment by MystPi** [comment]
Since its text is white and so is its background, it appears to have no text.

**Comment by ILOVETOMAKESTUFF** [comment]
Okay. To easily fix that, you could change the background color of the card to a grey?

**Comment by MystPi** [comment]
Yeah, you could, I was just demonstrating what would happen if you just changed the background color and the text color.

**Comment by ILOVETOMAKESTUFF** [comment]
I wish I knew how to use Tailwind… 😑

**Comment by ILOVETOMAKESTUFF** [comment]
How do you toggle the theme?

**Comment by ILOVETOMAKESTUFF** [comment]
No, in this site. Isn't there supposed to be like a button?

**Comment by MystPi** [comment]
I haven't added dark mode though.

**Comment by ILOVETOMAKESTUFF** [comment]
![image](https://user-images.githubusercontent.com/97681427/171885913-e46c0866-8c21-4833-be8c-bf6d363f2c24.png)

**Comment by MystPi** [comment]
Closing doesn't necessarily mean I implemented the request.

**Comment by ILOVETOMAKESTUFF** [comment]
Oh. But you closed it as completed, so doesn't that mean that you have completed the dark theme? (I'm sorry if I'm a nuisance)
