### ISSUE TITLE
Service Addition/Edit Request: Personal Stickies

### ISSUE THREAD

**Issue by Steve0Greatness** [MystPi/scratch-explorer#4]
**Name:** Personal Stickies

**For:** Forums

**Theme color:** Gray

**Description:** Save topics to your own profile.

**Icon:** person_pin_circle

**Forum topic (optional):** 604367

**Username:** Steve0Greatness

**Link:** https://personal-stickies.stevesgreatness.repl.co/

**Comment by MystPi** [comment]
I'll add it ASAP. Thanks for your request. :)

**Comment by MystPi** [comment]
Added: https://scratchexplorer.vercel.app/#p
